const tap = require('tap')
const path = require('path')
const solution = require('./solution')
const problemDay = path.basename(__dirname)

tap.test(`solution for ${problemDay} should work`, async assert => {
  assert.equal(solution(''), 0)
  assert.equal(solution('1'), 1)
  assert.equal(solution('9'), 1)
  assert.equal(solution('12'), 2)
  assert.equal(solution('26'), 2)
  assert.equal(solution('27'), 1)
  assert.equal(solution('1234'), 3)
  assert.equal(solution('1020'), 1)
  assert.equal(solution('1023'), 2)
  assert.equal(solution('12120'), 3)
  assert.equal(solution('13420'), 2)
  assert.equal(solution('16225'), 6)
})
