const tap = require('tap')
const path = require('path')
const solution = require('./solution')
const problemDay = path.basename(__dirname)

tap.test(`solution for ${problemDay} should work`, async assert => {
  assert.equal(solution(0), 0)
  assert.equal(solution(1), 1)
  assert.equal(solution(4), 4)
  assert.equal(solution(5), 1)
  assert.equal(solution(6), 2)
  assert.equal(solution(9), 5)
  assert.equal(solution(10), 1)
  assert.equal(solution(11), 2)
  assert.equal(solution(14), 5)
  assert.equal(solution(15), 2)
  assert.equal(solution(16), 3)
  assert.equal(solution(19), 6)
  assert.equal(solution(20), 2)
  assert.equal(solution(25), 1)
  assert.equal(solution(74), 8)
  assert.equal(solution(75), 3)
  assert.equal(solution(99), 9)
})
